### PR TITLE
Revert version

### PR DESCRIPTION
**Pull request by mikepmanning**
same as previous pull, but changed version back to 1

just reverting version back to 1

### CODE REVIEW

**Comment by JCalvinL** [comment]
I think having a pre-release or beta version to merge all commits from
contributors would be a good practice. When the pre-release is stable and
clean. It can the be merged with the master for public release.

**Comment by mikepmanning** [comment]
no problem with that

This is my first rodeo with github and using this stuff, so I'm mostly trying to get used to it, I figured this was a simple enough change that it could be pushed through

**Comment by vadi2** [comment]
@JCalvinL For the time being, all PRs are merged into master and are assumed to be quality checked (https://github.com/m-mf/m-mf/wiki/m&mf-design-principles) - the project can decide to change that later on if that's desired.

**Comment by vadi2** [comment]
Speaking of the above, doc/index.rst should be updated for the change in alias' functionality.

**Pull request merged**
