### PR TITLE
Add scripts needed to automate tests and releases

### PR DESCRIPTION
**Pull request by keneanung**
I'm the current maintainer of the m-mf sister system svof. A while ago I created an infrastructure to automate release creation and compile checks on PRs. @vadi2 asked me to do the same for m-mf.

This PR adds the needed scripts and files to m-mf. Tests and releases will not work yet though.

The second part will be setting up travis for compiling, documentation and release creation. For that I created a pseudo user @m-mf-machine-account, which will need to be part of the m-mf organisation and in a team with write permissions to the m-mf repository to push documentation. For setup it would also make things easier if it temporarily had admin permissions, so I can create the travis integration and other things without having to ask all the time.

### CODE REVIEW

**Comment by vadi2** [comment]
Thanks for setting this up! I've given temporary admin access to @m-mf-machine-account so you can set it all up.

**Comment by m-mf-machine-account** [comment]
Merging this now to continue the setup.

**Comment by keneanung** [comment]
I think I'm done with the setup. I will watch the next release closely though because that will be the real test.

If everything works, I'd be happy to yield control of the machine account to someone else.

Oh and sorry, I forgot again to change the git mail address and name, so I am noted as commit author...

**Comment by vadi2** [comment]
I've written up the steps for the last release on https://github.com/m-mf/m-mf/wiki/Release-process, does anything need to change?

**Comment by keneanung** [comment]
The current workflow in svof is:
1. Create a release including tag of the next version (for example `6`). No need to set anything besides tag name and title
2. Wait for the build to go through. This will set the body (changelog) and upload the zips.
3. Edit the changelog a little to make the changes understandable
4. Post on forums and news

So in your writeup, points 1-5, 7, 9 are not needed anymore and the rest are handled differently/in another order...

**Comment by mikepmanning** [comment]
It might be worth doing another release of v5 due to the errors people have reported with Macs. I'm not sure if it's because I loaded it up on my windows computer or what. That would allow for a test at the same time

**Comment by vadi2** [comment]
Good idea, Travis makes releases on Ubuntu so it would be same environment
I had.

**Comment by vadi2** [comment]
@keneanung, does the updated https://github.com/m-mf/m-mf/wiki/Release-process look accurate?

**Comment by keneanung** [comment]
@siddister I'm not 100% sure, but I think you'll need to delete the tag as well after deleting the release v5 to trigger a new Travis build.

@vadi2 Should be good. But I honestly never used a draft release but published it immediately, so I have no experience with drafts.

**Comment by mikepmanning** [comment]
Ok, deleted the tag and release, I'll try making a new one

**Comment by mikepmanning** [comment]
Draft release created - now we wait I suppose

**Comment by keneanung** [comment]
Hrm. Looks like draft releases don't start builds on Travis... You'll need to publish the release first.
@vadi2 I updated https://github.com/m-mf/m-mf/wiki/Release-process to reflect that.

**Comment by mikepmanning** [comment]
ok, published

**Comment by keneanung** [comment]
And done: https://github.com/m-mf/m-mf/releases/tag/5

BTW you can check the progress of the build on https://travis-ci.org/m-mf/m-mf

ETA: The changelog will reflect PRs only, so commits directly to "master" will need to be added manually.

**Comment by mikepmanning** [comment]
Awesome, Thanks man, very much appreciated!

**Comment by keneanung** [comment]
You're welcome. If it breaks or there are questions and you want me to have a look, tag me. And if you have a non-https server with FTP upload, it's also possible to port svof's auto update feature over.

**Pull request merged**
