### PR TITLE
Update NDB for Non-Binary

### PR DESCRIPTION
**Pull request by ashira104**
New Code in triggers for NameDB>Data Capture>Honors on a person>Honors

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MudletPackage>
<MudletPackage version="1.001">
	<TriggerPackage>
		<Trigger isActive="no" isFolder="no" isTempTrigger="no" isMultiline="no" isPerlSlashGOption="no" isColorizerTrigger="no" isFilterTrigger="no" isSoundTrigger="no" isColorTrigger="no" isColorTriggerFg="no" isColorTriggerBg="no">
			<name>Honors</name>
			<script>if ndb.honorsid then killTimer(ndb.honorsid) end

temp_name_list = {}
temp_name_list[1] = {
  name = ndb.honorsname, demigod = 0,
  guildenemy = 0, orgenemy = 0, immortal = 0,
--  gender = line:find("%f[%a][mM]ale%f[%A]") or line:find("%f[%a][nN]on%f[%A]-%f[%a][bB]inary[%A]") and 'male' or 'female' or 'non-binary',
  gender = 'male' or 'female' or 'Non-Binary',
  title = line:match("(.-) %(")
}

local brackets = line:match("%((.-)%)")
if brackets:find("%f[%a]God%f[%A]") or brackets:find("%f[%a]Goddess%f[%A]") or brackets:find("%f[%a]Ephemeral%f[%A]") or brackets:find("%f[%a]Divine%f[%A]") or brackets:find("%f[%a]Immortal%f[%A]") then
  temp_name_list[1].immortal = 1 
  temp_name_list[1].gender = ""
elseif brackets:find("Demigod",1,true) then
  temp_name_list[1].demigod = 1
end

ndb.honors_line_count = 0

local startline = getLineNumber()
for i = 1, 10 do -- word wrapping can mess it up, go so back a fair bit in case of small screen

  -- work backwards until the line with the name is located
  if string.find(getCurrentLine(), "%f[%a]"..ndb.honorsname.."%f[%A]") or getCurrentLine():starts("A small shrubbery") then
    -- pick up the race as it is listed
    local race = getCurrentLine():match("%(male (.-)%)") or getCurrentLine():match("%(female (.-)%)") or getCurrentLine():match("%(non-binary (.-)%)") or ""

    if ndb.isvalidrace(race) then
      temp_name_list[1].race = race:lower()
    end

    break
  end
  if ndb.gaghonours then deleteLine() end
  moveCursor(0, startline-i)
end
moveCursorEnd()</script>
			<triggerType>0</triggerType>
			<conditonLineDelta>0</conditonLineDelta>
			<mStayOpen>100</mStayOpen>
			<mCommand></mCommand>
			<packageName></packageName>
			<mFgColor>#ff0000</mFgColor>
			<mBgColor>#ffff00</mBgColor>
			<mSoundFile></mSoundFile>
			<colorTriggerFgColor>#000000</colorTriggerFgColor>
			<colorTriggerBgColor>#000000</colorTriggerBgColor>
			<regexCodeList>
				<string>return line:find("%f[%a]"..ndb.honorsname.."%f[%A]") and line:find("(", 1, true) and line:find(")", 1, true)</string>
				<string>A small shrubbery (</string>
			</regexCodeList>
			<regexCodePropertyList>
				<integer>4</integer>
				<integer>2</integer>
			</regexCodePropertyList>
			<Trigger isActive="yes" isFolder="no" isTempTrigger="no" isMultiline="no" isPerlSlashGOption="no" isColorizerTrigger="no" isFilterTrigger="no" isSoundTrigger="no" isColorTrigger="no" isColorTriggerFg="no" isColorTriggerBg="no">
				<name>XP rank</name>
				<script>temp_name_list[1].xp_rank = tonumber(matches[2])

-- 200 is a safe amount to set it at, as the number will vary
if tonumber(matches[2]) &lt; 200 then temp_name_list[1].demigod = 1 end</script>
				<triggerType>0</triggerType>
				<conditonLineDelta>0</conditonLineDelta>
				<mStayOpen>0</mStayOpen>
				<mCommand></mCommand>
				<packageName></packageName>
				<mFgColor>#ff0000</mFgColor>
				<mBgColor>#ffff00</mBgColor>
				<mSoundFile></mSoundFile>
				<colorTriggerFgColor>#000000</colorTriggerFgColor>
				<colorTriggerBgColor>#000000</colorTriggerBgColor>
				<regexCodeList>
					<string>^(?:She|He) is ranked (\d+)\w+ in Lusternia\.</string>
					<string>^They are ranked (\d+)\w+ in Lusternia\.</string>
				</regexCodeList>
				<regexCodePropertyList>
					<integer>1</integer>
					<integer>1</integer>
				</regexCodePropertyList>
			</Trigger>
			<Trigger isActive="yes" isFolder="no" isTempTrigger="no" isMultiline="no" isPerlSlashGOption="no" isColorizerTrigger="no" isFilterTrigger="no" isSoundTrigger="no" isColorTrigger="no" isColorTriggerFg="no" isColorTriggerBg="no">
				<name>Unranked</name>
				<script>temp_name_list[1].xp_rank = -2</script>
				<triggerType>0</triggerType>
				<conditonLineDelta>0</conditonLineDelta>
				<mStayOpen>0</mStayOpen>
				<mCommand></mCommand>
				<packageName></packageName>
				<mFgColor>#ff0000</mFgColor>
				<mBgColor>#ffff00</mBgColor>
				<mSoundFile></mSoundFile>
				<colorTriggerFgColor>#000000</colorTriggerFgColor>
				<colorTriggerBgColor>#000000</colorTriggerBgColor>
				<regexCodeList>
					<string>He is unranked in Lusternia.</string>
					<string>She is unranked in Lusternia.</string>
					<string>He has cut his thread from the Tapestry of the Fates.</string>
					<string>She has cut her thread from the Tapestry of the Fates.</string>
					<string>He is frozen in time and space.</string>
					<string>She is frozen in time and space.</string>
					<string>They are frozen in time and space.</string>
					<string>They have cut their thread from the Tapestry of the Fates.</string>
					<string>They are unranked in Lusternia.</string>
				</regexCodeList>
				<regexCodePropertyList>
					<integer>3</integer>
					<integer>3</integer>
					<integer>3</integer>
					<integer>3</integer>
					<integer>3</integer>
					<integer>3</integer>
					<integer>3</integer>
					<integer>3</integer>
					<integer>3</integer>
				</regexCodePropertyList>
			</Trigger>
			<Trigger isActive="yes" isFolder="no" isTempTrigger="no" isMultiline="no" isPerlSlashGOption="no" isColorizerTrigger="no" isFilterTrigger="no" isSoundTrigger="no" isColorTrigger="no" isColorTriggerFg="no" isColorTriggerBg="no">
				<name>Org &amp; rank</name>
				<script>local org = ndb.findfromtable(matches[3], ndb.valid.orgs)

if org then
  temp_name_list[1].org_rank = ndb.getorgrank(matches[2])
  temp_name_list[1].org = org
end</script>
				<triggerType>0</triggerType>
				<conditonLineDelta>0</conditonLineDelta>
				<mStayOpen>0</mStayOpen>
				<mCommand></mCommand>
				<packageName></packageName>
				<mFgColor>#ff0000</mFgColor>
				<mBgColor>#ffff00</mBgColor>
				<mSoundFile></mSoundFile>
				<colorTriggerFgColor>#000000</colorTriggerFgColor>
				<colorTriggerBgColor>#000000</colorTriggerBgColor>
				<regexCodeList>
					<string>^(?:He|She) is a (.+?) in the (.+)?\.</string>
					<string>^They are a (.+?) in the (.+)?\.</string>
				</regexCodeList>
				<regexCodePropertyList>
					<integer>1</integer>
					<integer>1</integer>
				</regexCodePropertyList>
			</Trigger>
			<Trigger isActive="yes" isFolder="no" isTempTrigger="no" isMultiline="no" isPerlSlashGOption="no" isColorizerTrigger="no" isFilterTrigger="no" isSoundTrigger="no" isColorTrigger="no" isColorTriggerFg="no" isColorTriggerBg="no">
				<name>Might</name>
				<script>temp_name_list[1].might = tonumber(matches[2])

-- toads are an It</script>
				<triggerType>0</triggerType>
				<conditonLineDelta>87</conditonLineDelta>
				<mStayOpen>0</mStayOpen>
				<mCommand></mCommand>
				<packageName></packageName>
				<mFgColor>#ff0000</mFgColor>
				<mBgColor>#ffff00</mBgColor>
				<mSoundFile></mSoundFile>
				<colorTriggerFgColor>#000000</colorTriggerFgColor>
				<colorTriggerBgColor>#000000</colorTriggerBgColor>
				<regexCodeList>
					<string>^(?:She|He|It) is considered to be approximately (\d+)% of your might\.$</string>
					<string>^They are considered to be approximately (\d+)% of your might\.$</string>
				</regexCodeList>
				<regexCodePropertyList>
					<integer>1</integer>
					<integer>1</integer>
				</regexCodePropertyList>
			</Trigger>
			<Trigger isActive="yes" isFolder="no" isTempTrigger="no" isMultiline="no" isPerlSlashGOption="no" isColorizerTrigger="no" isFilterTrigger="no" isSoundTrigger="no" isColorTrigger="no" isColorTriggerFg="no" isColorTriggerBg="no">
				<name>Equal might</name>
				<script>temp_name_list[1].might = 100</script>
				<triggerType>0</triggerType>
				<conditonLineDelta>0</conditonLineDelta>
				<mStayOpen>0</mStayOpen>
				<mCommand></mCommand>
				<packageName></packageName>
				<mFgColor>#ff0000</mFgColor>
				<mBgColor>#ffff00</mBgColor>
				<mSoundFile></mSoundFile>
				<colorTriggerFgColor>#000000</colorTriggerFgColor>
				<colorTriggerBgColor>#000000</colorTriggerBgColor>
				<regexCodeList>
					<string>He is considered to be approximately equal to your might.</string>
					<string>She is considered to be approximately equal to your might.</string>
					<string>They are considered to be approximately equal to your might.</string>
				</regexCodeList>
				<regexCodePropertyList>
					<integer>3</integer>
					<integer>3</integer>
					<integer>3</integer>
				</regexCodePropertyList>
			</Trigger>
			<Trigger isActive="yes" isFolder="no" isTempTrigger="no" isMultiline="no" isPerlSlashGOption="no" isColorizerTrigger="no" isFilterTrigger="no" isSoundTrigger="no" isColorTrigger="no" isColorTriggerFg="no" isColorTriggerBg="no">
				<name>Avatar</name>
				<script>temp_name_list[1].order = matches[2]</script>
				<triggerType>0</triggerType>
				<conditonLineDelta>0</conditonLineDelta>
				<mStayOpen>0</mStayOpen>
				<mCommand></mCommand>
				<packageName></packageName>
				<mFgColor>#ff0000</mFgColor>
				<mBgColor>#ffff00</mBgColor>
				<mSoundFile></mSoundFile>
				<colorTriggerFgColor>#000000</colorTriggerFgColor>
				<colorTriggerBgColor>#000000</colorTriggerBgColor>
				<regexCodeList>
					<string>(?:He|She) is an Avatar of (\w+),</string>
				</regexCodeList>
				<regexCodePropertyList>
					<integer>1</integer>
				</regexCodePropertyList>
			</Trigger>
			<Trigger isActive="yes" isFolder="no" isTempTrigger="no" isMultiline="no" isPerlSlashGOption="no" isColorizerTrigger="no" isFilterTrigger="no" isSoundTrigger="no" isColorTrigger="no" isColorTriggerFg="no" isColorTriggerBg="no">
				<name>City/Commune enemy</name>
				<script>temp_name_list[1].orgenemy = 1</script>
				<triggerType>0</triggerType>
				<conditonLineDelta>0</conditonLineDelta>
				<mStayOpen>0</mStayOpen>
				<mCommand></mCommand>
				<packageName></packageName>
				<mFgColor>#ff0000</mFgColor>
				<mBgColor>#ffff00</mBgColor>
				<mSoundFile></mSoundFile>
				<colorTriggerFgColor>#000000</colorTriggerFgColor>
				<colorTriggerBgColor>#000000</colorTriggerBgColor>
				<regexCodeList>
					<string>(?:He|She) is an enemy of your (?:commune|city)\.$</string>
					<string>They are an enemy of your (?:commune|city)\.$</string>
				</regexCodeList>
				<regexCodePropertyList>
					<integer>1</integer>
					<integer>1</integer>
				</regexCodePropertyList>
			</Trigger>
			<Trigger isActive="yes" isFolder="no" isTempTrigger="no" isMultiline="no" isPerlSlashGOption="no" isColorizerTrigger="no" isFilterTrigger="no" isSoundTrigger="no" isColorTrigger="no" isColorTriggerFg="no" isColorTriggerBg="no">
				<name>Guildenemy</name>
				<script>temp_name_list[1].guildenemy = 1</script>
				<triggerType>0</triggerType>
				<conditonLineDelta>0</conditonLineDelta>
				<mStayOpen>0</mStayOpen>
				<mCommand></mCommand>
				<packageName></packageName>
				<mFgColor>#ff0000</mFgColor>
				<mBgColor>#ffff00</mBgColor>
				<mSoundFile></mSoundFile>
				<colorTriggerFgColor>#000000</colorTriggerFgColor>
				<colorTriggerBgColor>#000000</colorTriggerBgColor>
				<regexCodeList>
					<string>He is an enemy of your guild.</string>
					<string>She is an enemy of your guild.</string>
					<string>They are an enemy of your guild.</string>
				</regexCodeList>
				<regexCodePropertyList>
					<integer>3</integer>
					<integer>3</integer>
					<integer>3</integer>
				</regexCodePropertyList>
			</Trigger>
			<Trigger isActive="yes" isFolder="no" isTempTrigger="no" isMultiline="no" isPerlSlashGOption="no" isColorizerTrigger="no" isFilterTrigger="no" isSoundTrigger="no" isColorTrigger="no" isColorTriggerFg="no" isColorTriggerBg="no">
				<name>Stop getting (honors)</name>
				<script>setTriggerStayOpen("Honors", 0)
disableTrigger("Honors")

-- didn't get honors - person has laurels?
if ndb.honors_line_count == 2 then
  -- don't erase namedb data with other false we might've collected then
  temp_name_list[1] = {laurels = 1, immortal = temp_name_list[1].immortal, gender = temp_name_list[1].gender, name = temp_name_list[1].name, demigod = temp_name_list[1].demigod}
end

db:merge_unique(ndb.db.people, temp_name_list)

local gaghonours = ndb.gaghonours
ndb.honorsid, ndb.gaghonours = nil, nil

raiseEvent("NameDB finished honors", temp_name_list[1].name, (gaghonours and "quiet" or "manual"))

temp_name_list = nil
ndb.honors_line_count = nil</script>
				<triggerType>0</triggerType>
				<conditonLineDelta>0</conditonLineDelta>
				<mStayOpen>0</mStayOpen>
				<mCommand></mCommand>
				<packageName></packageName>
				<mFgColor>#ff0000</mFgColor>
				<mBgColor>#ffff00</mBgColor>
				<mSoundFile></mSoundFile>
				<colorTriggerFgColor>#000000</colorTriggerFgColor>
				<colorTriggerBgColor>#000000</colorTriggerBgColor>
				<regexCodeList>
					<string>return isPrompt()</string>
				</regexCodeList>
				<regexCodePropertyList>
					<integer>4</integer>
				</regexCodePropertyList>
			</Trigger>
			<Trigger isActive="yes" isFolder="no" isTempTrigger="no" isMultiline="no" isPerlSlashGOption="no" isColorizerTrigger="no" isFilterTrigger="no" isSoundTrigger="no" isColorTrigger="no" isColorTriggerFg="no" isColorTriggerBg="no">
				<name>Any line</name>
				<script>if ndb.gaghonours then deleteLine() end

-- this can go off on the prompt when we're done with everything
if ndb.honors_line_count then
  ndb.honors_line_count = ndb.honors_line_count + 1
end</script>
				<triggerType>0</triggerType>
				<conditonLineDelta>99</conditonLineDelta>
				<mStayOpen>0</mStayOpen>
				<mCommand></mCommand>
				<packageName></packageName>
				<mFgColor>#ff0000</mFgColor>
				<mBgColor>#ffff00</mBgColor>
				<mSoundFile></mSoundFile>
				<colorTriggerFgColor>#000000</colorTriggerFgColor>
				<colorTriggerBgColor>#000000</colorTriggerBgColor>
				<regexCodeList>
					<string>return true</string>
				</regexCodeList>
				<regexCodePropertyList>
					<integer>4</integer>
				</regexCodePropertyList>
			</Trigger>
		</Trigger>
	</TriggerPackage>
</MudletPackage>

### CODE REVIEW

**Comment by mikepmanning** [comment]
Is this just a comment with code changes? I can merge it, but I'm not seeing any changes to this code.

**Comment by ashira104** [comment]
I've never submitted for a change before, so I likely did this wrong. But there's additions in there for non-binary in honours that MMF doesn't have.

**Comment by mikepmanning** [comment]
You'll want to clone this, edit the source code and then commit/push it as a pull request for the change to be merged/added

**Comment by vadi2** [comment]
@ashira104 can I help you in getting this completed?

**Comment by steingrim** [comment]
This can probably be closed now due to NDB update for non-binary (#127).

**Pull request closed without merging**
