### PR TITLE
Add release artifacts to github pages

### PR DESCRIPTION
**Pull request by keneanung**
This should enable automatic updates as soon as the update URLs inside the
packages are changed.

This is related to #2 

Signed-off-by: keneanung keneanung@googlemail.com

### CODE REVIEW

**Comment by mikepmanning** [comment]
Just to clarfy - I need to change the url in the import me file to:
http://m-mf.github.io/m-mf/releases or something?

I can update it, I'm just not sure the exact page

**Comment by keneanung** [comment]
I didn't look into the m-mf code about this, but if it#s like svof, it will download a "current_version" file first, which will be located at http://m-mf.github.io/m-mf/releases/current_version
Then it will download the actual package, which will be at http://m-mf.github.io/m-mf/releases/{class}.m-mf.v{version}.zip

**Comment by mikepmanning** [comment]
Merged this one - I updated the script file (hopefully correctly)

I'll do some testing to make sure it work

**Comment by mikepmanning** [comment]
though I suppose the only way to test is to make another release huh

**Pull request merged**
